name       : gts
version    : 0.7.6
release    : 1
source     :
    - https://sourceforge.net/projects/gts/files/gts/0.7.6/gts-0.7.6.tar.gz/download : 059c3e13e3e3b796d775ec9f96abdce8f2b3b5144df8514eda0cc12e13e8b81e
license    : LGPL-2.0
component  : programming.library
summary    : GTS stands for the GNU Triangulated Surface Library
description: |
    This is the GTS library. GTS stands for the GNU Triangulated Surface Library. It includes a number of useful functions to deal with triangulated surfaces including, but not limited to, multi-resolution models, Delaunay and Constrained Delaunay triangulations, set operations on surfaces (intersection, union etc ...), bounding-boxes trees for efficient collision and intersection detection, triangle strips generation for fast rendering.
builddeps  :
    - gcc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
